let _metadata = createMetadata({
 "TH1 HRtP - Eternal Shrine Maiden (永遠の巫女)":["TH1"],
 "TH1 HRtP - A Sacred Lot":["TH1"],
 "TH1 HRtP - A Soul Devoted to the Gods ~ Highly Responsive to Prayers (神へ捧げる魂 ～ Highly Responsive to Prayers)":["TH1"],
 "TH1 HRtP - Eastern Tale of Fancy (東方怪奇談)":["TH1"],
 "TH1 HRtP - Oriental Magician":["TH1"],
 "TH1 HRtP - Magic Mirror (魔鏡)":["TH1"],
 "TH1 HRtP - Yin and Yang ~ The Positive and Negative (陰陽 ～ The Positive and Negative)":["TH1"],
 "TH1 HRtP - Small Evil-Crushing Blade (破邪の小太刀)":["TH1"],
 "TH1 HRtP - the Legend of KAGE":["TH1"],
 "TH1 HRtP - Angel's Legend (天使伝説)":["TH1"],
 "TH1 HRtP - Now, Until the Moment You Die (いざ、倒れ逝くその時まで)":["TH1"],
 "TH1 HRtP - Civilization of Magic/We Shall Die Together/Theme of Turning to Hell (Theme of 地獄めくり / 死なばもろとも)":["TH1"],
 "TH1 HRtP - Angel of a Distant Star ~ The Alice in Wonderland Angel/Swordsman of a Distant Star (星幽天使 ～ The Alice in Wonderland Angel / 星幽剣士)":["TH1"],
 "TH1 HRtP - Iris (アイリス)":["TH1"],
 //Touhou 2 OST
 "TH2 SoEW - Hakurei ~ Eastern Wind (博麗 ～ Eastern Wind)":["TH2"],
 "TH2 SoEW - She's In A Temper!!":["TH2"],
 "TH2 SoEW - End of Daylight":["TH2"],
 "TH2 SoEW - Power of Darkness (やみのちから)":["TH2"],
 "TH2 SoEW - World of Fantasies (幻夢界)":["TH2"],
 "TH2 SoEW - Eastern Demon-Sealing Record ~ Pure Land Mandala (東方封魔録　～ 浄土曼荼羅)":["TH2"],
 "TH2 SoEW - Bet on Death (死を賭して)":["TH2"],
 "TH2 SoEW - Himorogi, Burn in Violet (ひもろぎ、むらさきにもえ)":["TH2"],
 "TH2 SoEW - Love-Colored Magic (恋色マジック)":["TH2"],
 "TH2 SoEW - Eastern Demon-Sealing Record ~ Spectral Boisterous Dance (東方封魔録 ～ 幽幻乱舞)":["TH2"],
 "TH2 SoEW - Complete Darkness":["TH2"],
 "TH2 SoEW - Legendary Wonderland/Crossing the Blue Sky (昔話わんだらーんど / 青空超えて)":["TH2"],
 "TH2 SoEW - Extra Love/Crazy Magic (エキストララブ / クレイジーマジック)":["TH2"],
 "TH2 SoEW - The Tank Girl's Dream (戦車むすめのみるゆめ)":["TH2"],
 "TH2 SoEW - Forest of Tono (遠野の森)":["TH2"],
 //Touhou 3 OST
 "TH3 PoDD - Mystic Oriental Love Consultation/Eastern Mystical Tale of Romance (東方妖恋談)":["TH3"],
 "TH3 PoDD - Selection":["TH3"],
 "TH3 PoDD - Reincarnation":["TH3"],
 "TH3 PoDD - Dim. Dream":["TH3"],
 "TH3 PoDD - Tabula rasa ~ The Empty Girl (Tabula rasa ～ 空白少女)":["TH3"],
 "TH3 PoDD - Decisive Magic Battle! ~ Fight it out! (魔法決戦！ ～ Fight it out!)":["TH3"],
 "TH3 PoDD - Maniacal Princess":["TH3"],
 "TH3 PoDD - Vanishing Dream ~ Lost Dream (夢消失 ～ Lost Dream)":["TH3"],
 "TH3 PoDD - Visionary Game ~ Dream War (夢幻遊戯 ～ Dream War)":["TH3"],
 "TH3 PoDD - Disunified Field Theory of Magic (非統一魔法世界論)":["TH3"],
 "TH3 PoDD - Adoration of Magic (魔法鐘愛)":["TH3"],
 "TH3 PoDD - Strawberry Crisis!!":["TH3"],
 "TH3 PoDD - Dream of Eternity (久遠の夢)":["TH3"],
 "TH3 PoDD - Eastern Blue Sky (東方の青い空)":["TH3"],
 "TH3 PoDD - A Dream Transcending Spacetime (夢は時空を越えて)":["TH3"],
 "TH3 PoDD - Eternal Full Moon (永遠の満月)":["TH3"],
 "TH3 PoDD - Sailor of Time":["TH3"],
 "TH3 PoDD - Maple Dream...":["TH3"],
 "TH3 PoDD - Ghostly Person's Holiday (霊人の休日)":["TH3"],
 //Touhou 4 OST
 "TH4 LLS - Gensokyo ~ Lotus Land Story (幻想郷 ～ Lotus Land Story)":["TH4"],
 "TH4 LLS - Witching Dream":["TH4"],
 "TH4 LLS - Selene's Light":["TH4"],
 "TH4 LLS - Decoration Battle (装飾戦 ～ Decoration Battle)":["TH4"],
 "TH4 LLS - Break the Sabbath":["TH4"],
 "TH4 LLS - Scarlet Symphony ~ Scarlet Phoneme (紅響曲 ～ Scarlet Phoneme)":["TH4"],
 "TH4 LLS - Bad Apple!!":["TH4"],
 "TH4 LLS - Spirit Battle ~ Perdition Crisis (霊戦 ～ Perdition crisis)":["TH4"],
 "TH4 LLS - Alice Maestra (アリスマエステラ)":["TH4"],
 "TH4 LLS - Maiden's Capriccio ~ Capriccio (少女綺想曲 ～ Capriccio)":["TH4"],
 "TH4 LLS - Vessel of Stars ~ Casket of Star (星の器 ～ Casket of Star)":["TH4"],
 "TH4 LLS - Lotus Love":["TH4"],
 "TH4 LLS - Cute Devil ~ Innocence (かわいい悪魔　～ Innocence)":["TH4"],
 "TH4 LLS - Sleeping Terror (眠れる恐怖 ～ Sleeping Terror)":["TH4"],
 "TH4 LLS - Dream Land":["TH4"],
 "TH4 LLS - Faint Dream ~ Inanimate Dream (幽夢 ～ Inanimate Dream)":["TH4"],
 "TH4 LLS - The Inevitably Forbidden Game (禁じざるをえない遊戯)":["TH4"],
 "TH4 LLS - Illusion of a Maid ~ Icemilk Magic (メイド幻想 ～ Icemilk Magic)":["TH4"],
 "TH4 LLS - Days":["TH4"],
 "TH4 LLS - Peaceful":["TH4"],
 "TH4 LLS - Arcadian Dream":["TH4"],
 "TH4 LLS - Those Who Live in Illusions (幻想の住人)":["TH4"],
 //Touhou 5 OST
 "TH5 MS - Bizarre Romantic Story ~ Mystic Square (怪綺談 ～ Mystic Square)":["TH5"],
 "TH5 MS - Dream Express":["TH5"],
 "TH5 MS - Magic Square (魔法陣 ～ Magic Square)":["TH5"],
 "TH5 MS - Dimension of Reverie (夢想時空)":["TH5"],
 "TH5 MS - Spiritual Heaven (霊天 ～ Spiritual Heaven)":["TH5"],
 "TH5 MS - Romantic Children":["TH5"],
 "TH5 MS - Plastic Mind (プラスチックマインド)":["TH5"],
 "TH5 MS - Soul's Resting Place (魂の休らむ所)":["TH5"],
 "TH5 MS - Maple Wise (メイプルワイズ)":["TH5"],
 "TH5 MS - Forbidden Magic (禁断の魔法 ～ Forbidden Magic)":["TH5"],
 "TH5 MS - Crimson Maiden ~ Crimson Dead!! (真紅の少女 ～ Crimson Dead!!)":["TH5"],
 "TH5 MS - Treacherous Maiden ~ Judas Kiss (裏切りの少女 ～ Judas Kiss)":["TH5"],
 "TH5 MS - The Last Judgement":["TH5"],
 "TH5 MS - Doll of Misery (悲しき人形　～ Doll of Misery)":["TH5"],
 "TH5 MS - End of the World ~ World's End (世界の果て ～ World's End)":["TH5"],
 "TH5 MS - Legendary Illusion ~ Infinite Being (神話幻想 ～ Infinite Being)":["TH5"],
 "TH5 MS - Alice in Wonderland (不思議の国のアリス)":["TH5"],
 "TH5 MS - the Grimoire of Alice":["TH5"],
 "TH5 MS - Shinto Shrine (神社)":["TH5"],
 "TH5 MS - Endless":["TH5"],
 "TH5 MS - Mystic Dream":["TH5"],
 "TH5 MS - Peaceful Romancer":["TH5"],
 "TH5 MS - Eternal Paradise (久遠の楽園)":["TH5"],
 //Touhou 6 OST
 "TH6 EoSD - A Dream More Scarlet than Red (赤より紅い夢)":["TH6"],
 "TH6 EoSD - A Soul as Scarlet as a Ground Cherry (ほおずきみたいに紅い魂)":["TH6"],
 "TH6 EoSD - Apparitions Stalk the Night (妖魔夜行)":["TH6"],
 "TH6 EoSD - Lunate Elf (ルーネイトエルフ)":["TH6"],
 "TH6 EoSD - Tomboyish Girl in Love (おてんば恋娘)":["TH6"],
 "TH6 EoSD - Shanghai Scarlet Teahouse ~ Chinese Tea (上海紅茶館 ～ Chinese Tea)":["TH6"],
 "TH6 EoSD - Shanghai Alice of Meiji 17 (明治十七年の上海アリス)" :["TH6"],
 "TH6 EoSD - Voile, the Magic Library (ヴワル魔法図書館)":["TH6"],
 "TH6 EoSD - An Eternity More Transient than Scarlet (紅より儚い永遠)":["TH6"],
 "TH6 EoSD - Locked Girl ~ The Girl's Sealed Room (ラクトガール　～ 少女密室)":["TH6"],
 "TH6 EoSD - The Maid and the Pocket Watch of Blood (メイドと血の懐中時計)":["TH6"],
 "TH6 EoSD - Lunar Clock ~ Luna Dial (月時計　～ ルナ・ダイアル)":["TH6"],
 "TH6 EoSD - The Young Descendant of Tepes (ツェペシュの幼き末裔)":["TH6"],
 "TH6 EoSD - Septette for a Dead Princess (亡き王女の為のセプテット)":["TH6"],
 "TH6 EoSD - The Centennial Festival for Magical Girls (魔法少女達の百年祭)":["TH6"],
 "TH6 EoSD - U.N. Owen Was Her? (U.N.オーエンは彼女なのか？)":["TH6"],
 "TH6 EoSD - Scarlet Chamber ~ Eastern Dream... (紅楼 ～ Eastern Dream...)":["TH6"],
 //Touhou 7 OST
 "TH7 PCB - Ghostly Dream ~ Snow or Cherry Petal (妖々夢 ～ Snow or Cherry Petal)":["TH7"],
 "TH7 PCB - Paradise ~ Deep Mountain (無何有の郷 ～ Deep Mountain)":["TH7"],
 "TH7 PCB - The Fantastic Legend of Tohno (遠野幻想物語)":["TH7"],
 "TH7 PCB - Diao Ye Zong (withered leaf) (ティアオイエツォン(withered leaf))":["TH7"],
 "TH7 PCB - The Doll Maker of Bucuresti (ブクレシュティの人形師)":["TH7"],
 "TH7 PCB - Doll Judgement ~ The Girl Who Played with People's Shapes (人形裁判 ～ 人の形弄びし少女)" :["TH7"],
 "TH7 PCB - The Capital City of Flowers in the Sky (天空の花の都)":["TH7"],
 "TH7 PCB - Phantom Band ~ Phantom Ensemble (幽霊楽団 ～ Phantom Ensemble)":["TH7"],
 "TH7 PCB - Eastern Ghostly Dream ~ Ancient Temple (東方妖々夢 ～ Ancient Temple)":["TH7"],
 "TH7 PCB - Crystallized Silver (クリスタライズシルバー)":["TH7"],
 "TH7 PCB - Hiroari Shoots a Strange Bird ~ Till When? (広有射怪鳥事 ～ Till When?)":["TH7"],
 "TH7 PCB - Ultimate Truth (アルティメットトゥルース)":["TH7"],
 "TH7 PCB - Bloom Nobly, Ink-Black Cherry Blossom ~ Border of Life (幽雅に咲かせ、墨染の桜 ～ Border of Life)" :["TH7"],
 "TH7 PCB - Border of Life (ボーダーオブライフ)":["TH7"],
 "TH7 PCB - A Maiden's Illusionary Funeral ~ Necro-Fantasy (少女幻葬 ～ Necro-Fantasy)":["TH7"],
 "TH7 PCB - Spiritual Domination ~ Who done it! (妖々跋扈 ～ Who done it!)":["TH7"],
 "TH7 PCB - Spiritual Domination (妖々跋扈)":["TH7"],
 "TH7 PCB - Necrofantasia (ネクロファンタジア)":["TH7"],
 "TH7 PCB - Dream of a Spring Breeze (春風の夢)":["TH7"],
 "TH7 PCB - Sakura, Sakura ~ Japanize Dream... (さくらさくら ～ Japanize Dream...)":["TH7"],
 //Touhou 7.5 OST
 "TH7.5 IaMP - Forgathering Dream (萃夢想)":["TH7.5"],
 "TH7.5 IaMP - Mystic Oriental Love Consultation/Eastern Mystical Tale of Romance (東方妖恋談)":["TH7.5"],
 "TH7.5 IaMP - Maiden's Capriccio (少女綺想曲 ～ Capriccio)":["TH7.5"],
 "TH7.5 IaMP - Love-Colored Magic (恋色マジック)":["TH7.5"],
 "TH7.5 IaMP - The Maid And The Pocket Watch of Blood (メイドと血の懐中時計)":["TH7.5"],
 "TH7.5 IaMP - Lunar Clock ~ Luna Dial (月時計 ～ ルナ・ダイアル)":["TH7.5"],
 "TH7.5 IaMP - The Doll Maker of Bucuresti (ブクレシュティの人形師)":["TH7.5"],
 "TH7.5 IaMP - Locked Girl ~ Girl's Secret Room (ラクトガール ～ 少女密室)":["TH7.5"],
 "TH7.5 IaMP - Voile, the Magic Library (ヴワル魔法図書館)":["TH7.5"],
 "TH7.5 IaMP - Hiroari Shoots A Strange Bird ~ Till When (広有射怪鳥事 ～ Till When?)":["TH7.5"],
 "TH7.5 IaMP - Eastern Ghostly Dream ~ Ancient Temple (東方妖々夢 ～ Ancient Temple)":["TH7.5"],
 "TH7.5 IaMP - Septette for a Dead Princess (亡き王女の為のセプテット)":["TH7.5"],
 "TH7.5 IaMP - Bloom Nobly, Ink-Black Cherry Blossom ~ Border of Life (幽雅に咲かせ、墨染の桜 ～ Border of Life)":["TH7.5"],
 "TH7.5 IaMP - Demystify Feast":["TH7.5"],
 "TH7.5 IaMP - Night Falls ~ Evening Star (夜が降りてくる ～ Evening Star)":["TH7.5"],
 "TH7.5 IaMP - The Fabled Land of Onigashima ~ Missing Power (御伽の国の鬼が島 ～ Missing Power)":["TH7.5"],
 "TH7.5 IaMP - End of Summer (夏明き)":["TH7.5"],
 "TH7.5 IaMP - Eastern Forgathering Dream (東方萃夢想)":["TH7.5"],
 "TH7.5 IaMP - Doll Judgement (人形裁判)":["TH7.5"],
 "TH7.5 IaMP - Bad Omen (禍機)":["TH7.5"],
 "TH7.5 IaMP - Demonic Place (魔所)":["TH7.5"],
 "TH7.5 IaMP - Eastern Wind (あゆのかぜ)":["TH7.5"],
 "TH7.5 IaMP - The Witches' Ball (魔女達の舞踏会)":["TH7.5"],
 "TH7.5 IaMP - Inner Heart (裏心)":["TH7.5"],
 "TH7.5 IaMP - Intermezzo" :["TH7.5"],
 "TH7.5 IaMP - Scarlet Night (紅夜)":["TH7.5"],
 "TH7.5 IaMP - Silence (森閑)":["TH7.5"],
 "TH7.5 IaMP - Skygazer (仰空)":["TH7.5"],
 "TH7.5 IaMP - The Moon (月輪)":["TH7.5"],
 "TH7.5 IaMP - Unexpected Visitor (珍客)":["TH7.5"],
 "TH7.5 IaMP - Wanderings (遍参)":["TH7.5"],
 "TH7.5 IaMP - Swift Battle (戦迅)":["TH7.5"],
 "TH7.5 IaMP - Broken Moon (砕月)":["TH7.5"],
 "TH7.5 IaMP - Solitary Place (幽境)":["TH7.5"],
 //Touhou 8 OST
 "TH8 IN - Eternal Dream ~ Mystic Maple (Eternal Dream ～ 幽玄の槭樹)":["TH8"],
 "TH8 IN - Evening Primrose (月見草)":["TH8"],
 "TH8 IN - Extend Ash ~ Person of Hourai (エクステンドアッシュ ～ 蓬莱人)":["TH8"],
 "TH8 IN - Reach for the Moon, Immortal Smoke (月まで届け、不死の煙)":["TH8"],
 "TH8 IN - Eastern Youkai Beauty (東方妖怪小町)":["TH8"],
 "TH8 IN - Illusionary Night ~ Ghostly Eyes (幻視の夜 ～ Ghostly Eyes)":["TH8"],
 "TH8 IN - Wriggling Autumn Moon ~ Mooned Insect (蠢々秋月 ～ Mooned Insect)":["TH8"],
 "TH8 IN - Song of the Night Sparrow ~ Night Bird (夜雀の歌声 ～ Night Bird)":["TH8"],
 "TH8 IN - Deaf to All but the Song (もう歌しか聞こえない)":["TH8"],
 "TH8 IN - Nostalgic Blood of the East ~ Old World (懐かしき東方の血 ～ Old World)":["TH8"],
 "TH8 IN - Plain Asia (プレインエイジア)":["TH8"],
 "TH8 IN - Retribution for the Eternal Night ~ Imperishable Night (永夜の報い ～ Imperishable Night)":["TH8"],
 "TH8 IN - Love-Colored Master Spark (恋色マスタースパーク)":["TH8"],
 "TH8 IN - Maiden's Capriccio ~ Dream Battle (少女綺想曲 ～ Dream Battle)":["TH8"],
 "TH8 IN - Cinderella Cage ~ Kagome, Kagome (シンデレラケージ ～ Kagome-Kagome)":["TH8"],
 "TH8 IN - Lunatic Eyes ~ Invisible Full Moon (狂気の瞳 ～ Invisible Full Moon)":["TH8"],
 "TH8 IN - Voyage 1969 (ヴォヤージュ1969)":["TH8"],
 "TH8 IN - Gensokyo Millennium ~ History of the Moon (千年幻想郷 ～ History of the Moon)":["TH8"],
 "TH8 IN - Flight of the Bamboo Cutter ~ Lunatic Princess (竹取飛翔 ～ Lunatic Princess)":["TH8"],
 "TH8 IN - Voyage 1970 (ヴォヤージュ1970)":["TH8"],
 "TH8 IN - Eternal Night Vignette ~ Eastern Night (永夜抄　～ Eastern Night)":["TH8"],
 //Touhou 9 OST
 "TH9 PoFV - The Flowers Remain in Fantasy (花は幻想のままに)":["TH9"],
 "TH9 PoFV - The Mound Where the Flowers Reflect (花の映る塚)":["TH9"],
 "TH9 PoFV - Mound of Shigan (此岸の塚)":["TH9"],
 "TH9 PoFV - Flower Reflecting Mound ~ Higan Retour (花映塚 ～ Higan Retour)":["TH9"],
 "TH9 PoFV - Wind God Girl (Short Version) (風神少女 (Short Version))":["TH9"],
 "TH9 PoFV - Higan Retour ~ Riverside View (彼岸帰航 ～ Riverside View)":["TH9"],
 "TH9 PoFV - Poison Body ~ Forsaken Doll (ポイズンボディ ～ Forsaken Doll)":["TH9"],
 "TH9 PoFV - Gensokyo, Past and Present ~ Flower Land (今昔幻想郷 ～ Flower Land)":["TH9"],
 "TH9 PoFV - Deaf to All but the Song ~ Flower Mix (もう歌しか聞こえない ～ Flower Mix)":["TH9"],
 "TH9 PoFV - Phantom Band ~ Phantom Ensemble (幽霊楽団 ～ Phantom Ensemble)":["TH9"],
 "TH9 PoFV - Spring Lane ~ Colorful Path (春色小径 ～ Colorful Path)":["TH9"],
 "TH9 PoFV - Lunatic Eyes ~ Invisible Full Moon (狂気の瞳 ～ Invisible Full Moon)":["TH9"],
 "TH9 PoFV - Adventure of the Lovestruck Tomboy (おてんば恋娘の冒険)":["TH9"],
 "TH9 PoFV - Oriental Dark Flight (オリエンタルダークフライト)":["TH9"],
 "TH9 PoFV - Flowering Night (フラワリングナイト)":["TH9"],
 "TH9 PoFV - Eastern Judgement in the Sixtieth Year ~ Fate of Sixty Years (六十年目の東方裁判 ～ Fate of Sixty Years)":["TH9"],
 "TH9 PoFV - White Flag of Usa Shrine (お宇佐さまの素い幡)":["TH9"],
 "TH9 PoFV - Eastern Ghostly Dream ~ Ancient Temple (東方妖々夢 ～ Ancient Temple)":["TH9"],
 "TH9 PoFV - Flower of Soul ~ Another Dream... (魂の花 ～ Another Dream...)":["TH9"],
 //Touhou 9.5 OST
 "TH9.5 StB - Tengu's Notebook ~ Mysterious Note (天狗の手帖 ～ Mysterious Note)":["TH9.5"],
 "TH9.5 StB - Sleepless Night of the Eastern Country (東の国の眠らない夜)":["TH9.5"],
 "TH9.5 StB - Retrospective Kyoto (レトロスペクティブ京都)":["TH9.5"],
 "TH9.5 StB - Tengu Is Watching ~ Black Eyes (天狗が見ている ～ Black Eyes)":["TH9.5"],
 "TH9.5 StB - Wind Circulation ~ Wind Tour (風の循環　～ Wind Tour)":["TH9.5"],
 //Touhou 10 OST
 "TH10 MoF - Akutagawa Ryuunosuke's Kappa ~ Candid Friend (芥川龍之介の河童 ～ Candid Friend)":["TH10"],
 "TH10 MoF - Fall of Fall ~ Autumnal Waterfall (フォールオブフォール ～ 秋めく滝)":["TH10"],
 "TH10 MoF - Youkai Mountain ~ Mysterious Mountain (妖怪の山 ～ Mysterious Mountain)":["TH10"],
 "TH10 MoF - The Primal Scene of Japan the Girl Saw (少女が見た日本の原風景)":["TH10"],
 "TH10 MoF - Cemetery of Onbashira ~ Grave of Being (御柱の墓場 ～ Grave of Being)":["TH10"],
 "TH10 MoF - The Venerable Ancient Battlefield ~ Suwa Foughten Field (神さびた古戦場 ～ Suwa Foughten Field)":["TH10"],
 "TH10 MoF - Sealed Gods (封印されし神々)":["TH10"],
 "TH10 MoF - The Gods Give Us Blessed Rain ~ Sylphid Dream (神は恵みの雨を降らす ～ Sylphid Dream)":["TH10"],
 "TH10 MoF - Tomorrow Will Be Special, Yesterday Was Not (明日ハレの日、ケの昨日)":["TH10"],
 "TH10 MoF - Faith Is for the Transient People (信仰は儚き人間の為に)":["TH10"],
 "TH10 MoF - Native Faith (ネイティブフェイス)":["TH10"],
 "TH10 MoF - A God That Misses People ~ Romantic Fall (人恋し神様 ～ Romantic Fall)":["TH10"],
 "TH10 MoF - Because Princess Inada is Scolding Me (稲田姫様に叱られるから)":["TH10"],
 "TH10 MoF - The Road of the Misfortune God ~ Dark Road (厄神様の通り道 ～ Dark Road)":["TH10"],
 "TH10 MoF - Dark Side of Fate (運命のダークサイド)":["TH10"],
 "TH10 MoF - The Gensokyo the Gods Loved (神々が恋した幻想郷)":["TH10"],
 "TH10 MoF - Shrine at the Foot of the Mountain (麓の神社)":["TH10"],
 "TH10 MoF - Player's Score (プレイヤーズスコア)":["TH10"],
 //Touhou 10.5
 "TH10.5 SWR - Heaven of Scarlet Perception (緋想天)":["TH10.5"],
 "TH10.5 SWR - Usual Days (日常坐臥)":["TH10.5"],
 "TH10.5 SWR - The Ground's Color is Yellow (地の色は黄色)":["TH10.5"],
 "TH10.5 SWR - Argue for and Against (甲論乙駁)":["TH10.5"],
 "TH10.5 SWR - Beautiful Nature Sight (風光明媚)":["TH10.5"],
 "TH10.5 SWR - Dancing Water Spray (踊る水飛沫)":["TH10.5"],
 "TH10.5 SWR - Fragrant Plants (香る樹葉花)":["TH10.5"],
 "TH10.5 SWR - Swing a Fish to Drive Away Flies (以魚駆蠅)":["TH10.5"],
 "TH10.5 SWR - Drunk as I Like (冷吟閑酔)":["TH10.5"],
 "TH10.5 SWR - Ridiculous Game (嘲りの遊戯)":["TH10.5"],
 "TH10.5 SWR - Free and Easy (放縦不羈)":["TH10.5"],
 "TH10.5 SWR - Skies Beyond the Clouds (雲外蒼天)":["TH10.5"],
 "TH10.5 SWR - Mystic Oriental Love Consultation/Eastern Mystical Tale of Romance (東方妖恋談)":["TH10.5"],
 "TH10.5 SWR - Vessel of Stars ~ Casket of Star (星の器 ～ Casket of Star)":["TH10.5"],
 "TH10.5 SWR - Flowering Night (フラワリングナイト)":["TH10.5"],
 "TH10.5 SWR - The Doll Maker of Bucuresti (ブクレシュティの人形師)":["TH10.5"],
 "TH10.5 SWR - Hiroari Shoots a Strange Bird ~ Till When? (広有射怪鳥事 ～ Till When？)":["TH10.5"],
 "TH10.5 SWR - Locked Girl ~ The Girl's Sealed Room (ラクトガール ～ 少女密室)":["TH10.5"],
 "TH10.5 SWR - Bloom Nobly, Ink-Black Cherry Blossom ~ Border of Life (幽雅に咲かせ、墨染の桜 ～ Border of Life)":["TH10.5"],
 "TH10.5 SWR - Catastrophe in Bhavaagra ~ Wonderful Heaven (有頂天変 ～ Wonderful Heaven)":["TH10.5"],
 "TH10.5 SWR - Septette for a Dead Princess (亡き王女の為のセプテット)":["TH10.5"],
 "TH10.5 SWR - Night Falls (夜が降りてくる)":["TH10.5"],
 "TH10.5 SWR - Broken Moon (砕月)":["TH10.5"],
 "TH10.5 SWR - Lunatic Eyes ~ Invisible Full Moon (狂気の瞳 ～ Invisible Full Moon)":["TH10.5"],
 "TH10.5 SWR - Wind God Girl (風神少女)":["TH10.5"],
 "TH10.5 SWR - Higan Retour ~ Riverside View (彼岸帰航 ～ Riverside View)":["TH10.5"],
 "TH10.5 SWR - Crimson in the Black Sea ~ Legendary Fish (黒い海に紅く ～ Legendary Fish)":["TH10.5"],
 "TH10.5 SWR - Flawless as Clothing of the Celestials (天衣無縫)":["TH10.5"],
 "TH10.5 SWR - Bhava-Agra As Seen Through a Child's Mind (幼心地の有頂天)":["TH10.5"],
 "TH10.5 SWR - Darkening Dusk (暮色蒼然)":["TH10.5"],
 "TH10.5 SWR - Eastern Heaven of Scarlet Perception (東方緋想天)":["TH10.5"],
 //Touhou 11 OST
 "TH11 SA - Hartmann's Youkai Girl (ハルトマンの妖怪少女)":["TH11"],
 "TH11 SA - The Dark Blowhole (暗闇の風穴)":["TH11"],
 "TH11 SA - The Sealed-Away Youkai ~ Lost Place (封じられた妖怪 ～ Lost Place)":["TH11"],
 "TH11 SA - The Bridge People No Longer Cross (渡る者の途絶えた橋)":["TH11"],
 "TH11 SA - Green-Eyed Jealousy (緑眼のジェラシー)":["TH11"],
 "TH11 SA - Corpse Voyage ~ Be of good cheer! (死体旅行 ～ Be of good cheer!)":["TH11"],
 "TH11 SA - Walking the Streets of a Former Hell (旧地獄街道を行く)":["TH11"],
 "TH11 SA - A Flower-Studded Sake Dish on Mt. Ooe (華のさかづき大江山)":["TH11"],
 "TH11 SA - Heartfelt Fancy (ハートフェルトファンシー)":["TH11"],
 "TH11 SA - Satori Maiden ~ 3rd eye (少女さとり ～ 3rd eye)":["TH11"],
 "TH11 SA - Lullaby of Deserted Hell (廃獄ララバイ)":["TH11"],
 "TH11 SA - Hellfire Mantle (業火マントル)":["TH11"],
 "TH11 SA - Solar Sect of Mystic Wisdom ~ Nuclear Fusion (霊知の太陽信仰 ～ Nuclear Fusion)":["TH11"],
 "TH11 SA - Awakening of the Earth Spirits (地霊達の起床)":["TH11"],
 "TH11 SA - The Earth Spirits' Homecoming (地霊達の帰宅)":["TH11"],
 "TH11 SA - Energy Daybreak ~ Future Dream... (エネルギー黎明 ～ Future Dream...)":["TH11"],
 "TH11 SA - Last Remote (ラストリモート)":["TH11"],
 //Touhou 12 OST
 "TH12 UFO - A Shadow in the Blue Sky (青空の影)":["TH12"],
 "TH12 UFO - At the Harbor of Spring (春の湊に)":["TH12"],
 "TH12 UFO - A Tiny, Tiny, Clever Commander (小さな小さな賢将)":["TH12"],
 "TH12 UFO - The Sealed Cloud Route (閉ざせし雲の通い路)":["TH12"],
 "TH12 UFO - Beware the Umbrella Left There Forever (万年置き傘にご注意を)":["TH12"],
 "TH12 UFO - Sky Ruin (スカイルーイン)":["TH12"],
 "TH12 UFO - The Traditional Old Man and the Stylish Girl (時代親父とハイカラ少女)":["TH12"],
 "TH12 UFO - Interdimensional Voyage of a Ghostly Passenger Ship (幽霊客船の時空を越えた旅)":["TH12"],
 "TH12 UFO - Captain Murasa (キャプテン・ムラサ)":["TH12"],
 "TH12 UFO - Rural Makai City Esoteria (魔界地方都市エソテリア)":["TH12"],
 "TH12 UFO - The Tiger-Patterned Bishamonten (虎柄の毘沙門天)":["TH12"],
 "TH12 UFO - Fires of Hokkai (法界の火)":["TH12"],
 "TH12 UFO - Emotional Skyscraper ~ Cosmic Mind (感情の摩天楼 ～ Cosmic Mind)":["TH12"],
 "TH12 UFO - UFO Romance in the Night Sky (夜空のユーフォーロマンス)":["TH12"],
 "TH12 UFO - Heian Alien (平安のエイリアン)":["TH12"],
 "TH12 UFO - Youkai Temple (妖怪寺)":["TH12"],
 "TH12 UFO - Returning Home from the Sky ~ Sky Dream (空の帰り道　～ Sky Dream)":["TH12"],
 //Touhou 12.3 OST
 "TH12.3 UNL - Did You See That Shadow? (君はあの影を見たか？)":["TH12.3"],
 "TH12.3 UNL - Forgathering Dream (萃夢想)":["TH12.3"],
 "TH12.3 UNL - The Legendary Titan (伝説の巨神)":["TH12.3"],
 "TH12.3 UNL - Our Hisoutensoku (ぼくらの非想天則)":["TH12.3"],
 "TH12.3 UNL - Scenery with Dolls (人形のある風景)":["TH12.3"],
 "TH12.3 UNL - The Eternal Steam Engine (悠久の蒸気機関)":["TH12.3"],
 "TH12.3 UNL - Faith Is for the Transient People (信仰は儚き人間の為に)":["TH12.3"],
 "TH12.3 UNL - Tomboyish Girl in Love (おてんば恋娘)":["TH12.3"],
 "TH12.3 UNL - Solar Sect of Mystic Wisdom ~ Nuclear Fusion (霊知の太陽信仰 ～ Nuclear Fusion)":["TH12.3"],
 "TH12.3 UNL - Shanghai Scarlet Teahouse ~ Chinese Tea (上海紅茶館 ～ Chinese Tea)":["TH12.3"],
 "TH12.3 UNL - Tomorrow Will Be Special, Yesterday Was Not (明日ハレの日、ケの昨日)":["TH12.3"],
 "TH12.3 UNL - Unknown X ~ Unfound Adventure (アンノウンＸ ～ Unfound Adventure)":["TH12.3"],
 "TH12.3 UNL - X, the Floating Object in the Sky (空に浮かぶ物体Ｘ)":["TH12.3"],
 "TH12.3 UNL - Dichromatic Lotus Butterfly ~ Ancients (二色蓮花蝶 ～ Ancients)":["TH12.3"],
 "TH12.3 UNL - Love-Colored Magic (恋色マジック)":["TH12.3"],
 "TH12.3 UNL - the Grimoire of Alice":["TH12.3"],
 "TH12.3 UNL - Voile, the Magic Library (ヴワル魔法図書館)":["TH12.3"],
 "TH12.3 UNL - Mystic Oriental Love Consultation/Eastern Mystical Tale of Romance (Century's End Version) (東方妖恋談 (世紀末バージョン))":["TH12.3"],
 //Touhou 12.5
 "TH12.5 DS - Youkai Modern Colony (妖怪モダンコロニー)":["TH12.5"],
 "TH12.5 DS - Nemesis' Stronghold (ネメシスの要塞)":["TH12.5"],
 "TH12.5 DS - The Mystery in Your Town (あなたの町の怪事件)":["TH12.5"],
 "TH12.5 DS - Newshound (ニュースハウンド)":["TH12.5"],
 "TH12.5 DS - Bell of Avici ~ Infinite Nightmare (無間の鐘　～ Infinite Nightmare)":["TH12.5"],
 "TH12.5 DS - The Youkai Mountain ~ Mysterious Mountain (妖怪の山　～ Mysterious Mountain)":["TH12.5"],
 //Touhou 12.8
 "TH12.8 GFW - An Ice Fairy in Spring (春の氷精)":["TH12.8"],
 "TH12.8 GFW - The Refrain of the Lovely Great War (可愛い大戦争のリフレーン)":["TH12.8"],
 "TH12.8 GFW - Year-Round Absorbed Curiosity (年中夢中の好奇心)":["TH12.8"],
 "TH12.8 GFW - Great Fairy Wars ~ Fairy Wars (妖精大戦争 ～ Fairy Wars)":["TH12.8"],
 "TH12.8 GFW - A Midnight Fairy Dance (真夜中のフェアリーダンス)":["TH12.8"],
 "TH12.8 GFW - Loose Rain (ルーズレイン)":["TH12.8"],
 "TH12.8 GFW - Magus Night (メイガスナイト)":["TH12.8"],
 "TH12.8 GFW - Staking Your Life on a Prank (いたずらに命をかけて)":["TH12.8"],
 "TH12.8 GFW - An Ice Fairy in Spring -Still- (春の氷精　- 静 -)":["TH12.8"],
 "TH12.8 GFW - Player's Score (プレイヤーズスコア)":["TH12.8"],
 //Touhou 13 OST
 "TH13 TD - Old Yuanxian (古きユアンシェン)":["TH13"],
 "TH13 TD - The Hall of Dreams' Great Mausoleum (夢殿大祀廟)":["TH13"],
 "TH13 TD - Omiwa Legend (大神神話伝)":["TH13"],
 "TH13 TD - Starry Sky of Small Desires (小さな欲望の星空)":["TH13"],
 "TH13 TD - Shoutoku Legend ~ True Administrator (聖徳伝説 ～ True Administrator)":["TH13"],
 "TH13 TD - Spirit of Avarice (欲深き霊魂)":["TH13"],
 "TH13 TD - Desire Dream (デザイアドリーム)":["TH13"],
 "TH13 TD - A New Wind at the Shrine (神社の新しい風)":["TH13"],
 "TH13 TD - Youkai Shrine's Back Road (妖怪裏参道)":["TH13"],
 "TH13 TD - Futatsuiwa from Sado (佐渡の二ッ岩)":["TH13"],
 "TH13 TD - Night Sakura of Dead Spirits (死霊の夜桜)":["TH13"],
 "TH13 TD - Ghost Lead (ゴーストリード)":["TH13"],
 "TH13 TD - Welcome to Youkai Temple (妖怪寺へようこそ)":["TH13"],
 "TH13 TD - Youkai Girl At The Gate (門前の妖怪小娘)":["TH13"],
 "TH13 TD - Let's Live In A Lovely Cemetery (素敵な墓場で暮しましょ)":["TH13"],
 "TH13 TD - Desire Drive (デザイアドライブ)":["TH13"],
 "TH13 TD - Rigid Paradise (リジッドパラダイス)":["TH13"],
 //Touhou 13.5 OST
 "TH13.5 HM - This Dull World's Unchanging Pessimism (塵界不変のペシミズム)":["TH13.5"],
 "TH13.5 HM - Shinkirou Orchestra (心綺楼囃子)":["TH13.5"],
 "TH13.5 HM - Performer Selection (演者選択)":["TH13.5"],
 "TH13.5 HM - A Popular Location (人気のある場所)":["TH13.5"],
 "TH13.5 HM - An Unpopular Location (人気のない場所)":["TH13.5"],
 "TH13.5 HM - Today's Front-Page Headline (本日の一面記事)":["TH13.5"],
 "TH13.5 HM - Spring Lane ~ Colorful Path (春色小径 ～ Colorful Path)":["TH13.5"],
 "TH13.5 HM - Magus Night (メイガスナイト)":["TH13.5"],
 "TH13.5 HM - The Traditional Old Man and the Stylish Girl (時代親父とハイカラ少女)":["TH13.5"],
 "TH13.5 HM - Emotional Skyscraper ~ Cosmic Mind (感情の摩天楼 ～ Cosmic Mind)":["TH13.5"],
 "TH13.5 HM - Omiwa Legend (大神神話伝)":["TH13.5"],
 "TH13.5 HM - Shoutoku Legend ~ True Administrator (聖徳伝説 ～ True Administrator)":["TH13.5"],
 "TH13.5 HM - Akutagawa Ryuunosuke's Kappa ~ Candid Friend (芥川龍之介の河童 ～ Candid Friend)":["TH13.5"],
 "TH13.5 HM - Hartmann's Youkai Girl (ハルトマンの妖怪少女)":["TH13.5"],
 "TH13.5 HM - Futatsuiwa from Gensokyo (幻想郷の二ッ岩)":["TH13.5"],
 "TH13.5 HM - The Village in the Dead of Night (丑三つ時の里)":["TH13.5"],
 "TH13.5 HM - The Lost Emotion (亡失のエモーション)":["TH13.5"],
 "TH13.5 HM - Morning Clouds (暁雲)":["TH13.5"],
 "TH13.5 HM - Officially-Sanctioned Twilight Newspaper (官板黄昏新聞)":["TH13.5"],
 "TH13.5 HM - Futatsuiwa from Sado (佐渡の二ッ岩)":["TH13.5"],
 "TH13.5 HM - Last Word Unleashed (ラストワード発動)":["TH13.5"],
 //Touhou 14 OST
 "TH14 DDC - Mysterious Purification Rod (不思議なお祓い棒)":["TH14"],
 "TH14 DDC - Mist Lake (ミストレイク)":["TH14"],
 "TH14 DDC - Mermaid from the Uncharted Land (秘境のマーメイド)":["TH14"],
 "TH14 DDC - Humans and Youkai Traversing the Canal (運河を行き交う人妖)":["TH14"],
 "TH14 DDC - Dullahan Under the Willows (柳の下のデュラハン)":["TH14"],
 "TH14 DDC - Bamboo Forest of the Full Moon (満月の竹林)":["TH14"],
 "TH14 DDC - Lonesome Werewolf (孤独なウェアウルフ)":["TH14"],
 "TH14 DDC - Magical Storm (マジカルストーム)":["TH14"],
 "TH14 DDC - Illusionary Joururi (幻想浄瑠璃)":["TH14"],
 "TH14 DDC - Mysterious Mysterious Tools (不思議な不思議な道具達)":["TH14"],
 "TH14 DDC - The Shining Needle Castle Sinking in the Air (空中に沈む輝針城)":["TH14"],
 "TH14 DDC - Reverse Ideology (リバースイデオロギー)":["TH14"],
 "TH14 DDC - The Exaggerated Castle Keep (針小棒大の天守閣)":["TH14"],
 "TH14 DDC - Inchlings of the Shining Needle ~ Little Princess (輝く針の小人族 ～ Little Princess)":["TH14"],
 "TH14 DDC - Thunderclouds of Magical Power (魔力の雷雲)":["TH14"],
 "TH14 DDC - Primordial Beat ~ Pristine Beat (始原のビート ～ Pristine Beat)":["TH14"],
 "TH14 DDC - Magical Power of the Mallet (小槌の魔力)":["TH14"],
 //Touhou 14.3 OST
 "TH14.3 ISC - Cheat Against the Impossible Danmaku (不可能弾幕には反則を)":["TH14.3"],
 "TH14.3 ISC - Midnight Spell Card (ミッドナイトスペルカード)":["TH14.3"],
 "TH14.3 ISC - Romantic Escape Flight (ロマンチック逃飛行)":["TH14.3"],
 "TH14.3 ISC - Raise the Signal Fire of Cheating (反則の狼煙を上げろ)":["TH14.3"],
 "TH14.3 ISC - Eternal Transient Reign (永遠の三日天下)":["TH14.3"],
 //Touhou 14.5 OST
 "TH14.5 ULiL - Heart-Stirring Urban Legends (心揺さぶる都市伝説)":["TH14.5"],
 "TH14.5 ULiL - Gensokyo Mystery Discovery (幻想郷ふしぎ発見)":["TH14.5"],
 "TH14.5 ULiL - An Everyday Life with Balls (ボールのある日常)":["TH14.5"],
 "TH14.5 ULiL - Occult à la Carte (オカルトアラカルト)":["TH14.5"],
 "TH14.5 ULiL - Forms of Manifested Folklore (顕現した伝承の形)":["TH14.5"],
 "TH14.5 ULiL - Seven-Orb Collection Showdown (七玉蒐集ショウダウン)":["TH14.5"],
 "TH14.5 ULiL - Fair Scramble (公正なる奪い合い)":["TH14.5"],
 "TH14.5 ULiL - Believe in Possibilities (可能性を信じて)":["TH14.5"],
 "TH14.5 ULiL - Arrival of the Winds of the Era (時代の風の訪れ)":["TH14.5"],
 "TH14.5 ULiL - The Value Is Unrealized (価値がわからない)":["TH14.5"],
 "TH14.5 ULiL - Those Who Know the Truth (真実を知る者)":["TH14.5"],
 "TH14.5 ULiL - Bell of the Antipodes (対蹠地の鐘)":["TH14.5"],
 "TH14.5 ULiL - Bamboo Forest in Flames (竹林インフレイム)":["TH14.5"],
 "TH14.5 ULiL - Hartmann's Youkai Girl (ハルトマンの妖怪少女)":["TH14.5"],
 "TH14.5 ULiL - The Arcane Is Revealed (明かされる深秘)":["TH14.5"],
 "TH14.5 ULiL - Battlefield of the Flower Threshold (華狭間のバトルフィールド)":["TH14.5"],
 "TH14.5 ULiL - Reach for the Moon Immortal Smoke (月まで届け、不死の煙)":["TH14.5"],
 "TH14.5 ULiL - Outside World Folklore (外界フォークロア)":["TH14.5"],
 "TH14.5 ULiL - Last Occultism ~ Esotericist of the Present World (ラストオカルティズム ～ 現し世の秘術師)":["TH14.5"],
 "TH14.5 ULiL - Each Ending (各々の結末)":["TH14.5"],
 "TH14.5 ULiL - Dichromatic Lotus Butterfly ~ Red and White (二色蓮花蝶 ～ Red and White)":["TH14.5"],
 "TH14.5 ULiL - Love-Colored Master Spark (恋色マスタースパーク)":["TH14.5"],
 "TH14.5 ULiL - The Traditional Old Man and the Stylish Girl (時代親父とハイカラ少女)":["TH14.5"],
 "TH14.5 ULiL - Emotional Skyscraper ~ Cosmic Mind (感情の摩天楼 ～ Cosmic Mind)":["TH14.5"],
 "TH14.5 ULiL - Omiwa Legend (大神神話伝)":["TH14.5"],
 "TH14.5 ULiL - Shoutoku Legend ~ True Administrator (聖徳伝説 ～ True Administrator)":["TH14.5"],
 "TH14.5 ULiL - Akutagawa Ryuunosuke's Kappa ~ Candid Friend (芥川龍之介の河童 ～ Candid Friend)":["TH14.5"],
 "TH14.5 ULiL - Futatsuiwa from Gensokyo (幻想郷の二ッ岩)":["TH14.5"],
 "TH14.5 ULiL - The Lost Emotion (亡失のエモーション)":["TH14.5"],
 "TH14.5 ULiL - Inchlings of the Shining Needle ~ Little Princess (輝く針の小人族 ～ Little Princess)":["TH14.5"],
 //Touhou 15 OST
 "TH15 LoLK - The Space Shrine Maiden Appears (宇宙巫女現る)":["TH15"],
 "TH15 LoLK - Unforgettable, the Nostalgic Greenery (忘れがたき、よすがの緑)":["TH15"],
 "TH15 LoLK - The Rabbit Has Landed (兎は舞い降りた)":["TH15"],
 "TH15 LoLK - The Lake Reflects the Cleansed Moonlight (湖は浄めの月光を映して)":["TH15"],
 "TH15 LoLK - September Pumpkin (九月のパンプキン)":["TH15"],
 "TH15 LoLK - The Mysterious Shrine Maiden Flying Through Space (宇宙を飛ぶ不思議な巫女)":["TH15"],
 "TH15 LoLK - Eternal Spring Dream (永遠の春夢)":["TH15"],
 "TH15 LoLK - Pandemonic Planet (パンデモニックプラネット)":["TH15"],
 "TH15 LoLK - The Frozen Eternal Capital (凍り付いた永遠の都)":["TH15"],
 "TH15 LoLK - The Reversed Wheel of Fortune (逆転するホイールオブフォーチュン)":["TH15"],
 "TH15 LoLK - Faraway Voyage of 380,000 Kilometers (遥か38万キロのボヤージュ)":["TH15"],
 "TH15 LoLK - Pierrot of the Star-Spangled Banner (星条旗のピエロ)":["TH15"],
 "TH15 LoLK - The Sea that Reflects One's Home Planet (故郷の星が映える海)":["TH15"],
 "TH15 LoLK - Pure Furies ~ Whereabouts of the Heart (ピュアヒューリーズ ～ 心の在処)":["TH15"],
 "TH15 LoLK - A World of Nightmares Never Seen Before (見た事も無い悪夢の世界)":["TH15"],
 "TH15 LoLK - The Moon as Seen from the Shrine (神社から見える月)":["TH15"],
 "TH15 LoLK - The Space Shrine Maiden Returns Home (宇宙巫女帰還する)":["TH15"],
 //Touhou 15.5 OST
 "TH15.5 AoCF - Seeds of the Incident (異変の種子)":["TH15.5"],
 "TH15.5 AoCF - Sprouts of Suspicion (疑惑の芽生え)":["TH15.5"],
 "TH15.5 AoCF - Branches Reaching to the Truth (真相へ繋がる枝葉)":["TH15.5"],
 "TH15.5 AoCF - Blizzard of Scattering Possession Flowers (舞い散る憑依華吹雪)":["TH15.5"],
 "TH15.5 AoCF - Being Things Eye To Eye (憑依投合)":["TH15.5"],
 "TH15.5 AoCF - Mushroom Waltz (マッシュルーム・ワルツ)":["TH15.5"],
 "TH15.5 AoCF - The One Jointly Responsible (連帯責人)":["TH15.5"],
 "TH15.5 AoCF - The Palanquin Ship Flies in the Sky (聖輦船空を往く)":["TH15.5"],
 "TH15.5 AoCF - Equality Under the Law of Dharma (法力の下の平等)":["TH15.5"],
 "TH15.5 AoCF - An Odd Couple (合縁奇縁)":["TH15.5"],
 "TH15.5 AoCF - The Ground's Color is Yellow ~ Primrose (地の色は黄色　～ Primrose)":["TH15.5"],
 "TH15.5 AoCF - Constant and Unchanging Temple of Worship (恒常不変の参廟祀)":["TH15.5"],
 "TH15.5 AoCF - Shining Armillary Sphere (光輝く天球儀)":["TH15.5"],
 "TH15.5 AoCF - Two Minds of One Body (異心同体)":["TH15.5"],
 "TH15.5 AoCF - The Ravine Kappa's Technological Prowess (沢の河童の技術力)":["TH15.5"],
 "TH15.5 AoCF - A Rose Blooming in the Underworld (地底に咲く薔薇)":["TH15.5"],
 "TH15.5 AoCF - In the Deep-Green Tanuki Forest (深緑の狸森にて)":["TH15.5"],
 "TH15.5 AoCF - Scheming Outside the Box (知略縦横)":["TH15.5"],
 "TH15.5 AoCF - Floating with the Tide (行雲流水)":["TH15.5"],
 "TH15.5 AoCF - Possession Flowers Yet to Bud (未だ蕾む憑依華)":["TH15.5"],
 "TH15.5 AoCF - Immortal Red Soul (不滅のレッドソウル)":["TH15.5"],
 "TH15.5 AoCF - Corridor Stretching to Eternity (永遠に続く回廊)":["TH15.5"],
 "TH15.5 AoCF - Grandiloquence (壮言大語)":["TH15.5"],
 "TH15.5 AoCF - The Inverted Castle Lit by the Setting Sun (落日に映える逆さ城)":["TH15.5"],
 "TH15.5 AoCF - Shinkirou Theatrical (心綺楼演舞)":["TH15.5"],
 "TH15.5 AoCF - In High Spirits (意気揚々)":["TH15.5"],
 "TH15.5 AoCF - Dream World Folklore (夢世界フォークロア)":["TH15.5"],
 "TH15.5 AoCF - Sleep Sheep Parade (スリープシープパレード)":["TH15.5"],
 "TH15.5 AoCF - Flawless as Clothing of the Celestials ~ Yellow Lily (天衣無縫 ～ Yellow Lily)":["TH15.5"],
 "TH15.5 AoCF - Bhavaagra as Far as the Eye Can See (至る有頂天)":["TH15.5"],
 "TH15.5 AoCF - Overcome a Thousand Trials (千の試練を超えて)":["TH15.5"],
 "TH15.5 AoCF - The Curtain Shall Rise Soon (開演間近)":["TH15.5"],
 "TH15.5 AoCF - Possession Flowers in Full Bloom (咲き誇る憑依華)":["TH15.5"],
 "TH15.5 AoCF - The Eternal Steam Engine (悠久の蒸気機関)":["TH15.5"],
 "TH15.5 AoCF - Yorimashi Between Dreams and Reality ~ Necro-Fantasia (憑坐は夢と現の間に ～ Necro-Fantasia)":["TH15.5"],
 "TH15.5 AoCF - Tonight Stars an Easygoing Egoist (Live ver.) ~ Egoistic Flowers. (今宵は飄逸なエゴイスト(Live ver)　～ Egoistic Flowers.)":["TH15.5"],
 "TH15.5 AoCF - Last Occultism ~ Esotericist of the Present World (ラストオカルティズム ～ 現し世の秘術師)":["TH15.5"],
 "TH15.5 AoCF - Eternal Spring Dream (永遠の春夢)":["TH15.5"],
 "TH15.5 AoCF - Inchlings of the Shining Needle ~ Little Princess (輝く針の小人族 ～ Little Princess)":["TH15.5"],
 "TH15.5 AoCF - Catastrophe in Bhavaagra ~ Wonderful Heaven (有頂天変 ～ Wonderful Heaven)":["TH15.5"],
 "TH15.5 AoCF - Battlefield of the Flower Threshold (華狭間のバトルフィールド)":["TH15.5"],
 "TH15.5 AoCF - Night Falls ~ Evening Star (夜が降りてくる ～ Evening Star)":["TH15.5"],
 "TH15.5 AoCF - Occult Attract (オカルトアトラクト)":["TH15.5"],
 "TH15.5 AoCF - Neo Bamboo Forest in Flames (ネオ竹林インフレイム)":["TH15.5"],
 "TH15.5 AoCF - Bell of So Many Aeons (億万劫の鐘)":["TH15.5"],
 "TH15.5 AoCF - Unknown X ~ Occultly Madness (アンノウンX　～ Occultly Madness)":["TH15.5"],
 //Touhou 16 OST
 "TH16 HSiFS - The Sky Where Cherry Blossoms Flutter Down (桜舞い散る天空)":["TH16"],
 "TH16 HSiFS - A Star of Hope Rises in the Blue Sky (希望の星は青霄に昇る)":["TH16"],
 "TH16 HSiFS - A Midsummer Fairy's Dream (真夏の妖精の夢)":["TH16"],
 "TH16 HSiFS - The Colorless Wind on Youkai Mountain (色無き風は妖怪の山に)":["TH16"],
 "TH16 HSiFS - Deep-Mountain Encounter (山奥のエンカウンター)":["TH16"],
 "TH16 HSiFS - Swim in a Cherry Blossom-Colored Sea (桜色の海を泳いで)":["TH16"],
 "TH16 HSiFS - A Pair of Divine Beasts (一対の神獣)":["TH16"],
 "TH16 HSiFS - Illusionary White Traveler (幻想のホワイトトラベラー)":["TH16"],
 "TH16 HSiFS - The Magic Straw-Hat Jizo (魔法の笠地蔵)":["TH16"],
 "TH16 HSiFS - Does the Forbidden Door Lead to This World, or the World Beyond? (禁断の扉の向こうは、この世かあの世か)":["TH16"],
 "TH16 HSiFS - No More Going Through Doors (もうドアには入れない)":["TH16"],
 "TH16 HSiFS - Crazy Backup Dancers (クレイジーバックダンサーズ)":["TH16"],
 "TH16 HSiFS - Into Backdoor (イントゥ・バックドア)":["TH16"],
 "TH16 HSiFS - The Concealed Four Seasons (秘匿されたフォーシーズンズ)":["TH16"],
 "TH16 HSiFS - Secret God Matara ~ Hidden Star in All Seasons. (秘神マターラ ～ Hidden Star in All Seasons.)":["TH16"],
 "TH16 HSiFS - Unnatural Nature (不自然な自然)":["TH16"],
 "TH16 HSiFS - White Traveler (白い旅人)":["TH16"],
 //Touhou 16.5 OST
 "TH16.5 VD - Nightmare Journal (悪夢日記)":["TH16.5"],
 "TH16.5 VD - Lucid Dreamer (ルーシッドドリーマー)":["TH16.5"],
 "TH16.5 VD - The Darkness Brought In by Swallowstone Naturalis Historia (燕石博物誌が連れてきた闇)":["TH16.5"],
 "TH16.5 VD - Old Adam Bar (バー・オールドアダム)":["TH16.5"],
 "TH16.5 VD - Lunatic Dreamer (ルナティックドリーマー)":["TH16.5"],
 "TH16.5 VD - Nightmare Diary (ナイトメアダイアリー)":["TH16.5"],
 //Touhou 17 OST
 "TH17 WBaWC - Silent Beast Spirits (物言わぬ獣の霊)":["TH17"],
 "TH17 WBaWC - The Lamentations Known Only to Jizo (地蔵だけが知る哀嘆)":["TH17"],
 "TH17 WBaWC - Jelly Stone (ジェリーストーン)":["TH17"],
 "TH17 WBaWC - Lost River (ロストリバー)":["TH17"],
 "TH17 WBaWC - The Stone Baby and the Submerged Bovine (石の赤子と水中の牛)":["TH17"],
 "TH17 WBaWC - Everlasting Red Spider Lily (不朽の曼珠沙華)":["TH17"],
 "TH17 WBaWC - Seraphic Chicken (セラフィックチキン)":["TH17"],
 "TH17 WBaWC - Unlocated Hell (アンロケイテッドヘル)":["TH17"],
 "TH17 WBaWC - Tortoise Dragon ~ Fortune and Misfortune (トータスドラゴン ～ 幸運と不運)":["TH17"],
 "TH17 WBaWC - Beast Metropolis (ビーストメトロポリス)":["TH17"],
 "TH17 WBaWC - Joutoujin of Ceramics (セラミックスの杖刀人)":["TH17"],
 "TH17 WBaWC - Electric Heritage (エレクトリックヘリテージ)":["TH17"],
 "TH17 WBaWC - Entrust this World to Idols ~ Idolatrize World (偶像に世界を委ねて ～ Idoratrize World)":["TH17"],
 "TH17 WBaWC - The Shining Law of the Strong Eating the Weak (輝かしき弱肉強食の掟)":["TH17"],
 "TH17 WBaWC - Prince Shoutoku's Pegasus ~ Dark Pegasus (聖徳太子のペガサス ～ Dark Pegasus)":["TH17"],
 "TH17 WBaWC - The Animal's Rest (畜生達の休息)":["TH17"],
 "TH17 WBaWC - Returning Home From The Underground (地下からの帰還)":["TH17"],
 //Touhou 17.5 OST
 "TH17.5 SFW - Submerged Hell of Sunken Sorrow (水没した沈愁地獄)":["TH17.5"],
 "TH17.5 SFW - Magician's Melancholy (魔法使いの憂鬱)":["TH17.5"],
 "TH17.5 SFW - Love-Colored Master Spark (恋色マスタースパーク)":["TH17.5"],
 "TH17.5 SFW - Maiden's Capriccio (少女綺想曲)":["TH17.5"],
 "TH17.5 SFW - The Dark Blowhole (暗闇の風穴)":["TH17.5"],
 "TH17.5 SFW - Beware the Umbrella Left There Forever (万年置き傘にご注意を)":["TH17.5"],
 "TH17.5 SFW - The Sealed-Away Youkai (封じられた妖怪)":["TH17.5"],
 "TH17.5 SFW - Walking the Streets of a Former Hell (旧地獄街道を行く)":["TH17.5"],
 "TH17.5 SFW - A Flower-Studded Sake Dish on Mt. Ooe (華のさかづき大江山)":["TH17.5"],
 "TH17.5 SFW - Cemetery of Onbashira (御柱の墓場)":["TH17.5"],
 "TH17.5 SFW - The Venerable Ancient Battlefield (神さびた古戦場)":["TH17.5"],
 "TH17.5 SFW - Captain Murasa (キャプテンムラサ)":["TH17.5"],
 "TH17.5 SFW - Hellfire Mantle (業火マントル)":["TH17.5"],
 "TH17.5 SFW - Solar Sect of Mystic Wisdom (霊知の太陽信仰)":["TH17.5"],
 "TH17.5 SFW - Everlasting Red Spider Lily (不朽の曼珠沙華)":["TH17.5"],
 "TH17.5 SFW - Seraphic Chicken (セラフィックチキン)":["TH17.5"],
 "TH17.5 SFW - Tonight Stars an Easygoing Egoist ~ Egoistic Flowers (今宵は飄逸なエゴイスト ～ Egoistic Flowers)":["TH17.5"],
 "TH17.5 SFW - The Centennial Festival for Magical Girls (魔法少女達の百年祭)":["TH17.5"],
 "TH17.5 SFW - U.N. Owen Was Her? (U.N.オーエンは彼女なのか？)":["TH17.5"],
 "TH17.5 SFW - Depths of the Earth, Ocean of Avarice (大地の底、剛欲の海)":["TH17.5"],
 "TH17.5 SFW - Memento of the Avaricious Beast (強欲な獣のメメント)":["TH17.5"],
 "TH17.5 SFW - Memento of All Organisms ~ Memory of Fossil Energy. (有機体全てのメメント ～ Memory of Fossil Energy.)":["TH17.5"],
 "TH17.5 SFW - Laws of Heaven, Desires of Man (天理人欲)":["TH17.5"],
 "TH17.5 SFW - Eastern Strange Tale of Avarice (東方剛欲異聞)":["TH17.5"],
 "TH17.5 SFW - No More Going Through Doors (もうドアには入れない)":["TH17.5"],
 "TH17.5 SFW - Secret God Matara (秘神マターラ)":["TH17.5"],
 //Touhou 18 OST
 "TH18 UM - A Rainbow Spanning Gensokyo (虹の架かる幻想郷)":["TH18"],
 "TH18 UM - A Shower of Strange Occurrences (妖異達の通り雨)":["TH18"],
 "TH18 UM - Kitten of Great Fortune (大吉キトゥン)":["TH18"],
 "TH18 UM - The Cliff Hidden in Deep Green (深緑に隠された断崖)":["TH18"],
 "TH18 UM - The Perpetual Snow of Komakusa Blossoms (駒草咲くパーペチュアルスノー)":["TH18"],
 "TH18 UM - Smoking Dragon (スモーキングドラゴン)":["TH18"],
 "TH18 UM - The Obsolescent Industrial Remains (廃れゆく産業遺構)":["TH18"],
 "TH18 UM - Banditry Technology (バンデットリィテクノロジー)":["TH18"],
 "TH18 UM - Ore from the Age of the Gods (神代鉱石)":["TH18"],
 "TH18 UM - The Long-Awaited Oumagatoki (待ちわびた逢魔が時)":["TH18"],
 "TH18 UM - Starry Mountain of Tenma (星降る天魔の山)":["TH18"],
 "TH18 UM - Lunar Rainbow (ルナレインボー)":["TH18"],
 "TH18 UM - Where Is That Bustling Marketplace Now ~ Immemorial Marketeers (あの賑やかな市場は今どこに ～ Immemorial Marketeers)":["TH18"],
 "TH18 UM - The Great Fantastic Underground Railway Network (幻想の地下大線路網)":["TH18"],
 "TH18 UM - The Princess Who Slays Dragon Kings (龍王殺しのプリンセス)":["TH18"],
 "TH18 UM - The Sunday After the Storm (嵐の後の日曜日)":["TH18"],
 "TH18 UM - A Rainbow-Colored World (虹色の世界)":["TH18"],
 //Touhou 18.5 OST
 "TH18.5 HBM - The Collector's Melancholy Afternoon (コレクターの憂鬱な午後)":["TH18.5"],
 "TH18.5 HBM - An Exciting and Familiar Gensokyo (ワクワクする見慣れた幻想郷)":["TH18.5"],
 "TH18.5 HBM - Black Markets Can Happen Anywhere Anytime (闇市場は場所を選ばない)":["TH18.5"],
 "TH18.5 HBM - The 100th Black Market (１００回目のブラックマーケット)":["TH18.5"],
 "TH18.5 HBM - Take Thy Danmaku In Hand O Bulletphiles (弾幕を持て、バレットフィリア達よ)":["TH18.5"],
 "TH18.5 HBM - Youkai Hook On (妖怪フックオン)":["TH18.5"],
 //Touhou 19 OST
 "TH19 UDoALG - A Beast's Intelligence (獣の知性)":["TH19"],
 "TH19 UDoALG - Pre-Battle Theme":["TH19"],
 "TH19 UDoALG - The World Is Made in an Adorable Way (世界は可愛く出来ている)":["TH19"],
 "TH19 UDoALG - The Oni on the Perpetual Mountain (鬼は悠久の山に)":["TH19"],
 "TH19 UDoALG - Magical Beast Scramble (魔獣スクランブル)":["TH19"],
 "TH19 UDoALG - Tiny Shangri-La (タイニーシャングリラ)":["TH19"],
 "TH19 UDoALG - A Brave and Leisurely Beast (勇敢で有閑な妖獣)":["TH19"],
 "TH19 UDoALG - Vampiric Cryptid Chupacabra (吸血怪獣チュパカブラ)":["TH19"],
 "TH19 UDoALG - The Path to Yomi Where None Turn Back (振り向かない黄泉の道)":["TH19"],
 "TH19 UDoALG - The Deviants' Unobstructed Light ~ Kingdom of Nothingness. (逸脱者達の無礙光 ～ Kingdom of Nothingness.)":["TH19"],
 "TH19 UDoALG - Beast Kings' Rest (獣王達の休息)":["TH19"],
 "TH19 UDoALG - Do Beasts Have Intelligence? (獣に知性はあるか)":["TH19"],
 //Touhou 20 OST
 "TH20 FW - Shrine Maiden Crowned with Glory (錦の上の巫女)":["TH20"],
 "TH20 FW - Beloved Dust Dwelling (愛おしき塵の住処)":["TH20"],
 "TH20 FW - Even if Forgotten by the World (例え世界から忘れられても)":["TH20"],
 "TH20 FW - Sacred Forest (セイクリッドフォレスト)":["TH20"],
 "TH20 FW - There is a Monster in the Woods (森にはお化けがいるよ)":["TH20"],
 "TH20 FW - Golden Land of Prester John (プレステ・ジョアンの黄金境)":["TH20"],
 "TH20 FW - Might as Well Stake Your Life to Solve the Riddle (どうせなら命を賭けて謎を解け)":["TH20"],
 "TH20 FW - Four-Color Labyrinth (フォーカラーラビリンス)":["TH20"],
 "TH20 FW - Reminiscence of Deer Hunting (鹿狩りのレミニセンス)":["TH20"],
 "TH20 FW - The Maiden Sinking into the Deep Sea of Memory (記憶の深海に沈む少女)":["TH20"],
 "TH20 FW - Watatsuki's Spell Card ~ Divine Sea Battle (綿月のスペルカード　〜 神海戦)":["TH20"],
 "TH20 FW - Sacred Precincts of the Pyramid (ピラミッドの神域)":["TH20"],
 "TH20 FW - Because I'm Used to Being the Last One Left ~ Stone Goddess (最後の一人は慣れてるから　〜 Stone Goddess)":["TH20"],
 "TH20 FW - Fantastic Drift (ファンタスティックドリフト)":["TH20"],
 "TH20 FW - Hallucination Atop a Bivalve (二枚貝の上のハルシネーション)":["TH20"],
 "TH20 FW - Unchanging Daily Life (不変の日常)":["TH20"],
 "TH20 FW - Beloved Daily Life (愛おしき日常)":["TH20"],
 "TH20 FW - To a World With Life and Death (生と死のある世界へ)":["TH20"],   
    })
/* --- PASTE THIS BELOW THE METADATA LIST --- */

// We use 'var' here to prevent "Identifier has already been declared" errors
var currentHeardle = null;
var stats;
var parsedStats;

function createMetadata(mtd) {
    let m = {}
    for(const soundtrack in mtd) {
        m[soundtrack] = {
            'game': mtd[soundtrack][0],
        }
    }
    return m
}

function _onSubmit() {
}

function appendMetadata(guess, row) {
    if(!guess.isCorrect) {
        // Safety check: ensure currentHeardle is set
        if (!currentHeardle || !currentHeardle.correctAnswer) return;

        let guessMeta = _metadata[guess.answer]
        let heardleMeta = _metadata[currentHeardle.correctAnswer]
        if(guessMeta && heardleMeta) {
            const metaEvaluation = document.createElement("div");
            const isCorrectGame = heardleMeta.game === guessMeta.game;
            guess.isCorrectGame = isCorrectGame; 
            metaEvaluation.innerHTML = `<div><div><span style="color: #38a11e; font-weight:bold;">${isCorrectGame ? `Correct Game!` : `<span style="color: #b92727; font-weight:bold;">Wrong Game</span>`}</span></div></div>`;
            row.appendChild(metaEvaluation);
        }
    }
}

function setCurrentHeardle(l) {
    currentHeardle = l; 
    setTimeout(() => {
        const rows = document.querySelectorAll("body > main > div.w-full.flex.flex-col.flex-grow.relative > div > div > div");
        
        // Safety: Stop if the game interface hasn't loaded rows yet
        if (!rows || rows.length === 0) return;

        stats = localStorage.getItem("userStats")
        if(stats != null ) {
            try {
                parsedStats = JSON.parse(stats);
                
                // Safety: Find stats ONLY for this specific song
                // (In infinite mode, random songs might not have stats, this prevents crashing)
                const songStats = parsedStats.find(p => p.correctAnswer == currentHeardle.correctAnswer);
                
                if (songStats && songStats.guessList) {
                    songStats.guessList.forEach((guess, index) => {
                        // Logic for replaying guesses (if needed)
                    })
                }
            } catch (e) {
                console.log("Stats error ignored:", e);
            }
        }
    }, 200)
}

function evaluateGuessMetadata(v) {
    const rows = document.querySelectorAll("body > main > div.w-full.flex.flex-col.flex-grow.relative > div > div > div");
    if (!rows.length || !v.length) return;

    const last = v[v.length-1]
    if (rows[v.length-1]) {
        appendMetadata(last, rows[v.length-1]);
    }
}